"""Colour-coded diff view with line-number gutter.

Replaces the plain ``QPlainTextEdit`` that was used through Stage 3-8 as
a temporary diff viewer. Uses :func:`src.core.diff_parser.parse_diff_lines`
to classify each line and paints backgrounds accordingly:

* Additions  — green-tinted background
* Deletions  — red-tinted background
* Hunk headers (``@@ … @@``) — cyan-tinted background
* Context / empty lines — transparent (the editor background shows through)

A gutter on the left draws the **file** line number for each change —
additions and context use the new-file line, deletions use the
old-file line, both derived from the parsed hunk header. The user
sees "this addition lives on line 42 of the file" rather than a
sequential 1, 2, 3 … diff index.

File-level header lines (``diff --git``, ``index``, ``--- a/…``,
``+++ b/…``, ``old mode``, etc.) are not displayed: the viewer is
opened from a specific file, so the file header is redundant noise.

The widget is read-only and has no file-io or Git logic — it only
receives a diff string via :meth:`set_diff`.

View modes
----------
The top of the widget carries a small centred toolbar with two checkable
buttons that toggle between **Changes only** and **Full document**:

* **Changes only** (default) — the diff as generated by ``git diff`` with
  ``context_lines=3``, just like every prior version. Best when the user
  only wants to see what changed.
* **Full document** — the same file rendered with effectively unlimited
  context so every line of both versions is present. The additions,
  deletions and hunks appear in the same colour-coded form as in the
  changes-only view; only the unchanged context expands to cover the
  whole file. Switching to this mode (or loading a new diff in this
  mode) auto-scrolls to the first change so the user lands on it
  without hunting through the file head.

The widget stores both variants of the diff text and renders whichever
matches the active mode, so toggling is instant (no re-diff needed).
Upstream code is expected to call :meth:`set_diff_pair` (or the legacy
:meth:`set_diff` + :meth:`set_full_document_diff`) when a new file is
selected; the toolbar then decides which variant to show.

Custom scrollbar
----------------
The vertical scrollbar is a :class:`_DiffScrollBar` that paints as a
minimap of the diff:

* Wider than the platform default so a thin vertical line in the
  middle can split it into two halves.
* **Left half** — red tick mark for every deletion, positioned by
  its file line number.
* **Right half** — green tick mark for every addition, positioned
  the same way.
* Background and thumb use alpha-blended colours so the bar reads
  as semi-transparent without breaking hit-testing.
"""
from __future__ import annotations

from enum import IntEnum

from PySide6.QtCore import QRect, QSize, Qt, QTimer, Signal
from PySide6.QtGui import (
    QColor,
    QFont,
    QPainter,
    QTextCharFormat,
    QTextCursor,
    QTextDocument,
)
from PySide6.QtWidgets import (
    QButtonGroup,
    QHBoxLayout,
    QPlainTextEdit,
    QPushButton,
    QScrollBar,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from src.core.diff_parser import DiffLineType, ParsedDiffLine, parse_diff_lines

# ── diff colour palette ───────────────────────────────────────────────
ADDITION_BG = QColor(26, 64, 32)
DELETION_BG = QColor(64, 32, 32)
HUNK_BG = QColor(26, 48, 64)
GUTTER_BG = QColor(21, 21, 21)
GUTTER_FG = QColor(90, 90, 90)
ADDITION_FG = QColor(172, 229, 172)
DELETION_FG = QColor(229, 172, 172)
HUNK_FG = QColor(140, 190, 210)
# ──────────────────────────────────────────────────────────────────────

ExtraSelection = QTextEdit.ExtraSelection

# How many characters of padding to leave on the right edge of the
# gutter before the diff text starts. Mirrors the value the old
# implementation used (digits + 3).
_GUTTER_RIGHT_PADDING_CHARS = 3

# Symmetric vertical padding around the toolbar's button row.
# Equal top and bottom so the buttons read as visually centred
# against both the widget edge above and the editor body below.
_TOOLBAR_VERTICAL_MARGIN = 4

# Default scrollbar width on Windows is ~16px. The custom scrollbar
# needs to fit two halves + a divider. We use an *odd* width so the
# centre column sits at an integer pixel — this gives us exact 10+1+10
# splits at any DPI scale, with no half-pixel offset to confuse the eye.
_SCROLLBAR_WIDTH = 21

# ── minimap-style scrollbar colours ───────────────────────────────────
# Background paints alpha-blended so the bar looks semi-transparent
# against the editor (the widget itself stays opaque — setting
# ``WA_TranslucentBackground`` interferes with hit-testing).
# Darker than the editor body so the marker colours pop and the
# bar reads as a distinct rail rather than as a continuation of
# the gutter background.
_SCROLLBAR_BG = QColor(18, 18, 18, 200)
# Divider is intentionally *dim* so it reads as a quiet boundary
# rather than as content — a bright divider pulled either side
# toward it visually, so we make it only slightly brighter than the
# background and let the colour contrast of the two halves do the
# real visual work.
_SCROLLBAR_DIVIDER = QColor(90, 90, 90, 200)
_SCROLLBAR_THUMB = QColor(220, 220, 220, 150)
_SCROLLBAR_THUMB_BORDER = QColor(80, 80, 80, 200)
_SCROLLBAR_DELETION = QColor(220, 70, 70, 230)
_SCROLLBAR_ADDITION = QColor(70, 200, 110, 230)

# Marker rectangles are drawn solid-filled rather than as thin
# lines so adjacent markers in line-number order overlap into a
# single visible block. The half-height is the radius around the
# marker's centre position — a 16-px-tall rectangle (8 px each way)
# comfortably spans the typical line-to-line gap on a long diff
# while staying small enough not to merge two unrelated hunks.
_SCROLLBAR_MARKER_HALF_HEIGHT = 8


def _cluster_indices_to_blocks(
    indices: list[int], total: int, gap_threshold: int = 2,
) -> list[tuple[float, float]]:
    """Group consecutive ``indices`` into ``(start, end)`` blocks.

    Each block is a half-open range in ``[0, 1]``:

    * ``start`` is the cluster's first index divided by ``total``
      — the position of the first line.
    * ``end`` is the cluster's last index + 1 divided by ``total``
      — the position of the line *after* the cluster, so the block
      visually fills the slot each line occupies on the bar.

    Using ``end_index + 1`` (instead of ``end_index``) makes
    adjacent blocks of different colours touch exactly at the
    boundary — the red block ends where the green block begins,
    with no gap. For the very last cluster in a colour, the +1
    caps naturally at 1.0 and the block runs to the bottom of
    the bar.

    Two indices belong to the same cluster when their numeric
    distance is at most ``gap_threshold``; clusters are returned
    in ascending index order. The colour boundary within a hunk
    (red → green) is always a separator because the two lists are
    clustered independently.
    """
    if not indices:
        return []
    sorted_indices = sorted(indices)
    blocks: list[tuple[float, float]] = []
    cluster_start = sorted_indices[0]
    cluster_end = sorted_indices[0]
    for index in sorted_indices[1:]:
        if index - cluster_end <= gap_threshold:
            cluster_end = index
            continue
        blocks.append((
            cluster_start / total,
            (cluster_end + 1) / total,
        ))
        cluster_start = index
        cluster_end = index
    blocks.append((
        cluster_start / total,
        (cluster_end + 1) / total,
    ))
    return blocks
# ──────────────────────────────────────────────────────────────────────


class DiffViewMode(IntEnum):
    """What the diff pane should display."""

    CHANGES_ONLY = 0
    FULL_DOCUMENT = 1


class _DiffScrollBar(QScrollBar):
    """Vertical scrollbar visualised as a minimap of the diff.

    The widget is wider than the platform default
    (:data:`_SCROLLBAR_WIDTH`); a thin vertical line in the middle
    splits it into two halves.

    * The **left half** paints horizontal red tick lines at the
      relative position of every deletion.
    * The **right half** does the same in green for additions.

    Both halves share a single semi-transparent thumb (sized from
    ``pageStep()`` / ``maximum()`` and positioned from ``value()``),
    so scrolling the document moves the same indicator over both
    halves at once. The whole bar background is drawn with a low alpha
    so it reads as semi-transparent against the editor body — the
    widget itself stays opaque so input still works.

    Public API
    ----------
    set_diff_blocks
        Hand in normalised ``(start, end)`` ranges for deletions /
        additions. Each range is rendered as one solid filled block
        so a hunk reads as a continuous coloured region rather than
        as a stack of overlapping thin lines.
    """

    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(Qt.Orientation.Vertical, parent)
        self._deletion_blocks: list[tuple[float, float]] = []
        self._addition_blocks: list[tuple[float, float]] = []
        # Force the width through several size hints so the host
        # widget's layout manager (which manages the scrollbar when
        # it is installed via ``setVerticalScrollBar``) cannot shrink
        # or stretch it on us. Without this, native styles on some
        # platforms report a smaller default extent and the bar ends
        # up with a paint area that is *one pixel less* than the
        # requested width — which is exactly enough to make the
        # 50/50 split look skewed (9+2+8 instead of 9+2+9).
        self.setFixedWidth(_SCROLLBAR_WIDTH)

    def sizeHint(self) -> QSize:  # noqa: N802 - Qt naming
        """Always report our preferred width regardless of style hints."""
        return QSize(_SCROLLBAR_WIDTH, super().sizeHint().height())

    def minimumSizeHint(self) -> QSize:  # noqa: N802 - Qt naming
        """Don't let the host shrink us below the preferred width."""
        return QSize(_SCROLLBAR_WIDTH, super().minimumSizeHint().height())

    def set_diff_blocks(
        self,
        deletions: list[tuple[float, float]],
        additions: list[tuple[float, float]],
    ) -> None:
        """Replace the block lists. Each entry is ``(start, end)``
        in ``[0, 1]``. Values are clamped so callers don't have to be
        careful about the exact ratio. The widget repaints immediately.

        ``deletions`` blocks are drawn on the left half, ``additions``
        on the right half. Adjacent blocks of different colours stay
        separate because each block is exactly the size of its
        cluster — no overlap by construction.
        """
        self._deletion_blocks = [
            (
                max(0.0, min(1.0, float(s))),
                max(0.0, min(1.0, float(e))),
            )
            for s, e in deletions
        ]
        self._addition_blocks = [
            (
                max(0.0, min(1.0, float(s))),
                max(0.0, min(1.0, float(e))),
            )
            for s, e in additions
        ]
        self.update()

    def paintEvent(self, event) -> None:  # noqa: N802
        """Replace the platform scrollbar painting with the minimap look.

        PySide6 doesn't expose ``SE_ScrollBarSlider`` via
        :class:`QStyle.SubElement`, so we compute the thumb rect
        ourselves from ``value()`` / ``maximum()`` / ``pageStep()``.
        The math mirrors what Qt's default style does internally.

        Why ``contentsRect`` instead of ``rect``
        ----------------------------------------
        ``self.rect()`` reports the widget's *outer* geometry, but
        some native styles (Windows in particular) reserve a 1-pixel
        border on one or both sides of a ``QScrollBar``. Painting into
        ``self.rect()`` puts our marker bars behind that border, which
        shifts everything one column and breaks the 50/50 split
        the user sees in real life (even when an offscreen test
        environment, which uses a styleless paint, looks balanced).
        ``self.contentsRect()`` is the inner area the host platform
        actually expects us to draw into, so we use that.

        Layout
        ------
        The ``contentsRect`` is split exactly in half; the centre
        column (integer for the odd :data:`_SCROLLBAR_WIDTH`) becomes
        the divider. With width 21 that's ``10 + 1 + 10`` — both
        halves the same pixel count, divider exactly centred, and
        no fractional offsets to worry about at any DPI.
        """
        painter = QPainter(self)
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)
        # Use the contents rect, not the widget rect — see the
        # docstring for why.
        rect = self.contentsRect()

        # 1) Semi-transparent background. The widget itself is opaque
        # so mouse events still work — the visual cue is achieved by
        # using alpha-blended fills instead.
        painter.fillRect(rect, _SCROLLBAR_BG)

        # 2) Two equal halves + a 1-px centre divider.
        half_w = rect.width() // 2
        left_rect = QRect(
            rect.left(), rect.top(), half_w, rect.height(),
        )
        right_rect = QRect(
            rect.left() + half_w + 1, rect.top(), rect.width() - half_w - 1,
            rect.height(),
        )
        divider_x = rect.left() + half_w

        # Marker region (leaving room for the thumb ends).
        pad = 3
        usable_top = rect.top() + pad
        usable_height = rect.height() - 2 * pad
        if usable_height <= 0:
            painter.end()
            return

        # 3) Markers — drawn as solid filled rectangles, one per cluster
        # of consecutive lines. Each cluster spans the full extent of
        # its group, so a hunk reads as one continuous coloured block
        # rather than as a stack of overlapping thin lines. Because
        # red and green clusters are computed independently they never
        # overlap on the bar — they sit at the actual positions of the
        # deletions and additions in the displayed diff.
        for start, end in self._deletion_blocks:
            # ``end`` is the position of the line *after* the
            # cluster, so a block for indices ``[a, b]`` spans
            # ``y(a) .. y(b+1)`` and butts directly against the
            # next colour's block at the boundary — no gap.
            y_start = int(usable_top + start * usable_height)
            y_end = int(usable_top + end * usable_height)
            block_height = max(y_end - y_start, 3)
            painter.fillRect(
                left_rect.left(), y_start,
                left_rect.width(), block_height,
                _SCROLLBAR_DELETION,
            )
        for start, end in self._addition_blocks:
            y_start = int(usable_top + start * usable_height)
            y_end = int(usable_top + end * usable_height)
            block_height = max(y_end - y_start, 3)
            painter.fillRect(
                right_rect.left(), y_start,
                right_rect.width(), block_height,
                _SCROLLBAR_ADDITION,
            )

        # 4) Divider — exactly one column, dead-centre.
        painter.fillRect(
            divider_x, rect.top(), 1, rect.height(), _SCROLLBAR_DIVIDER,
        )

        # 5) Thumb. Size is proportional to the visible fraction of
        # the document so the user gets the same "this much of the
        # file is in view" cue they'd get from a regular scrollbar;
        # position uses the live ``value()``.
        #
        # We only ``fillRect`` the thumb and *do not* draw a border:
        # ``drawRect`` paints the outline at the rect's outer edge,
        # which — once antialiasing is factored in — bleeds one
        # pixel past the fill area and partially obscures the
        # topmost marker (the one that sits right below the thumb).
        # The fill alone reads clearly against the rest of the
        # bar; the border is decorative and not worth the artefact.
        thumb_rect = self._compute_thumb_rect(rect, pad)
        if not thumb_rect.isNull() and thumb_rect.isValid():
            painter.fillRect(thumb_rect, _SCROLLBAR_THUMB)

        painter.end()

    def _compute_thumb_rect(self, rect: QRect, pad: int) -> QRect:
        """Return the thumb rectangle for the current scrollbar state.

        PySide6 doesn't expose ``SE_ScrollBarSlider`` via
        :class:`QStyle.SubElement`, so we compute the geometry from
        ``value()`` / ``maximum()`` / ``minimum()`` directly. The
        math mirrors Qt's standard slider proportion: thumb height is
        ``pageStep / (pageStep + range)`` of the usable area, the
        position is interpolated from ``value()``.
        """
        slider_min = self.minimum()
        slider_max = self.maximum()
        slider_range = slider_max - slider_min
        usable_height = rect.height() - 2 * pad
        if usable_height <= 0 or slider_range <= 0:
            return QRect()
        page_step = max(1, self.pageStep())
        # Visible fraction of the document — same formula Qt uses
        # internally for scrollbar thumbs.
        thumb_height = max(
            24,
            min(
                int(page_step / (page_step + slider_range) * usable_height),
                usable_height,
            ),
        )
        if thumb_height >= usable_height:
            return QRect(rect.left(), rect.top() + pad, rect.width(), thumb_height)
        travel = usable_height - thumb_height
        value = max(slider_min, min(slider_max, self.value()))
        offset = int((value - slider_min) / slider_range * travel)
        return QRect(
            rect.left(), rect.top() + pad + offset, rect.width(), thumb_height,
        )


class _LineNumberArea(QWidget):
    """Left gutter that paints the file line number for each block."""

    def __init__(self, editor: _DiffEditor) -> None:
        super().__init__(editor)
        self._editor = editor

    def sizeHint(self) -> QSize:  # noqa: N802
        return QSize(self._editor.gutter_width(), 0)

    def paintEvent(self, event) -> None:  # noqa: N802
        painter = QPainter(self)
        painter.fillRect(event.rect(), GUTTER_BG)
        block = self._editor.firstVisibleBlock()
        top = round(
            self._editor.blockBoundingGeometry(block)
            .translated(self._editor.contentOffset())
            .top()
        )
        bottom = top + round(self._editor.blockBoundingRect(block).height())
        fm = self._editor.fontMetrics()
        w = self.width() - fm.horizontalAdvance("9")
        line_info = self._editor._line_info
        while block.isValid() and top <= event.rect().bottom():
            if block.isVisible() and bottom >= event.rect().top():
                block_num = block.blockNumber()
                line_number = (
                    line_info[block_num].line_number
                    if block_num < len(line_info)
                    else None
                )
                if line_number is not None:
                    painter.setPen(GUTTER_FG)
                    painter.drawText(
                        0,
                        top,
                        w,
                        fm.height(),
                        Qt.AlignmentFlag.AlignRight,
                        str(line_number),
                    )
            block = block.next()
            top = bottom
            bottom = top + round(self._editor.blockBoundingRect(block).height())
        painter.end()


class _DiffEditor(QPlainTextEdit):
    """Internal plain-text editor that collaborates with the gutter."""

    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self.setReadOnly(True)
        self.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.setFont(QFont("Consolas", 10))
        self.setTabStopDistance(40)
        # Parallel to the editor's blocks: for each visible block we
        # remember its semantic type and (when applicable) the real
        # file line number, so the gutter can paint the file row
        # instead of a sequential index.
        self._line_info: list[ParsedDiffLine] = []
        self._line_number_area = _LineNumberArea(self)
        # Custom scrollbar — see :class:`_DiffScrollBar` for the
        # two-half minimap visualisation (red deletions on the
        # left, green additions on the right, semi-transparent
        # through alpha-blended paints).
        self._diff_scrollbar = _DiffScrollBar(self)
        self.setVerticalScrollBar(self._diff_scrollbar)
        self.blockCountChanged.connect(self._update_gutter_width)
        self.updateRequest.connect(self._update_line_number_area)

    def gutter_width(self) -> int:
        """Width required to fit the longest line number we display.

        Sized off the maximum file line number (not the visible block
        count) so a single-line change in a 1000-line file still gets
        a 4-digit gutter.
        """
        max_block = max(self.blockCount(), 1)
        max_line = max(
            (info.line_number for info in self._line_info if info.line_number),
            default=0,
        )
        digits = len(str(max(max_block, max_line)))
        digits = max(1, digits)
        fm = self.fontMetrics()
        return fm.horizontalAdvance("9") * (digits + _GUTTER_RIGHT_PADDING_CHARS)

    def line_number_area_width(self) -> int:
        return self.gutter_width()

    def set_line_info(self, line_info: list[ParsedDiffLine]) -> None:
        """Replace the parallel block-to-line mapping.

        Must be called whenever the editor's text changes so block N
        in the document still corresponds to the right
        :class:`ParsedDiffLine`.
        """
        self._line_info = list(line_info)
        # Recompute gutter width now that the max line number may
        # have changed; ``blockCountChanged`` only fires when the
        # number of blocks changes, not when their metadata does.
        self._update_gutter_width()

    def update_diff_markers(self, line_info: list[ParsedDiffLine]) -> None:
        """Push the diff's deletion/addition blocks to the scrollbar.

        Markers are positioned by their **index in the displayed
        diff document**, normalised by the total number of visible
        lines, and then grouped into clusters of consecutive
        indices. Each cluster becomes one solid filled block on the
        scrollbar.

        The index-based positioning gives two guarantees:

        * **Red and green never overlap.** Within a hunk the
          deletions precede the additions in the diff text, so
          the red cluster always ends at a smaller index than the
          green cluster begins. The blocks sit at the actual
          positions of those lines in the diff — red on top,
          green below — exactly the way they appear on screen.
        * **Scrolling lands on the right line.** Clicking a block
          moves the editor's viewport to that fraction of the
          content, which *is* the line the block represents — no
          off-by-N mismatch with file line numbers the scrollbar
          isn't aware of.

        A cluster is one or more indices with no gap between
        adjacent entries. ``gap_threshold`` (in number of
        intervening indices) determines where one cluster ends and
        the next begins; with the default of 2, every non-adjacent
        colour boundary in the diff becomes a separator between
        blocks.
        """
        total = len(line_info)
        if total == 0:
            self._diff_scrollbar.set_diff_blocks([], [])
            return
        deletion_indices = [
            index
            for index, info in enumerate(line_info)
            if info.line_type == DiffLineType.DELETION
        ]
        addition_indices = [
            index
            for index, info in enumerate(line_info)
            if info.line_type == DiffLineType.ADDITION
        ]
        if not deletion_indices and not addition_indices:
            self._diff_scrollbar.set_diff_blocks([], [])
            return
        deletion_blocks = _cluster_indices_to_blocks(
            deletion_indices, total,
        )
        addition_blocks = _cluster_indices_to_blocks(
            addition_indices, total,
        )
        self._diff_scrollbar.set_diff_blocks(deletion_blocks, addition_blocks)

    # ── internal slots connected to signals ───────────────────────

    def _update_gutter_width(self, _new_block_count: int = 0) -> None:
        self.setViewportMargins(self.gutter_width(), 0, 0, 0)

    def _update_line_number_area(self, rect: QRect, dy: int) -> None:
        if dy:
            self._line_number_area.scroll(0, dy)
        else:
            self._line_number_area.update(
                0, rect.y(), self._line_number_area.width(), rect.height(),
            )
        if rect.contains(self.viewport().rect()):
            self._update_gutter_width()

    def resizeEvent(self, event) -> None:  # noqa: N802
        super().resizeEvent(event)
        cr = self.contentsRect()
        self._line_number_area.setGeometry(
            cr.left(), cr.top(), self.gutter_width(), cr.height(),
        )


class DiffViewWidget(QWidget):
    """Colour-coded, read-only diff viewer with a line-number gutter.

    Usage
    -----
    >>> view = DiffViewWidget(parent)
    >>> view.set_diff(diff_text)                     # changes-only text
    >>> view.set_full_document_diff(full_diff_text)  # full-document text
    >>> view.set_view_mode(DiffViewMode.FULL_DOCUMENT)
    >>> view.clear()

    A two-button toolbar at the top lets the user flip between
    *Changes only* and *Full document*; the rest of the widget is the
    colour-coded diff pane described in the module docstring. Callers
    that pre-compute both variants should hand them to
    :meth:`set_diff_pair` to keep toggling instantaneous.

    File-level header lines (``diff --git`` / ``---`` / ``+++`` /
    ``index`` / mode lines) are not shown — the user picked this
    view from a specific file, so the header is redundant. The
    gutter paints the actual file line number for every change so
    the reader can see "this addition is on line 42 of the file"
    instead of a sequential diff index.
    """

    view_mode_changed = Signal(object)
    """Emitted with the new :class:`DiffViewMode` when the user toggles
    the toolbar buttons (also fires when the mode is set programmatically
    via :meth:`set_view_mode`, but only when the value actually changes)."""

    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self._editor = _DiffEditor(self)
        self._changes_only_text: str = ""
        self._full_document_text: str = ""
        self._view_mode: DiffViewMode = DiffViewMode.CHANGES_ONLY
        self._build_toolbar()
        self._layout_body()

    # ── layout ────────────────────────────────────────────────────

    # ── stylesheet (active button is visually distinct) ──────────
    #
    # The default ``QPushButton`` checked-state rendering is so subtle
    # on Windows that the user can't tell which mode is active. The
    # stylesheet paints the *checked* button with the theme accent so
    # the active mode is unmissable. Colours match :data:`DARK_THEME`
    # (``bg_panel``, ``accent``/``accent_hover``/``accent_pressed``,
    # ``text_on_accent``); the widget is theme-agnostic today so the
    # literals are duplicated rather than threaded through the theme
    # system.
    _BUTTON_STYLESHEET = (
        "QPushButton {"
        " background-color: transparent;"
        " color: #D4D4D4;"
        " border: 1px solid #3F3F46;"
        " border-radius: 3px;"
        " padding: 4px 12px;"
        " font-weight: 500;"
        "}"
        "QPushButton:hover { background-color: #2A2D2E; }"
        "QPushButton:checked {"
        " background-color: #007ACC;"
        " color: #FFFFFF;"
        " border-color: #007ACC;"
        "}"
        "QPushButton:checked:hover { background-color: #1F8AD2; }"
        "QPushButton:pressed { background-color: #005A9E; }"
        "QPushButton:focus { outline: none; }"
    )

    def _build_toolbar(self) -> None:
        """Create the two-mode toggle buttons that sit above the editor.

        The buttons are wrapped in a :class:`QButtonGroup` so only one
        can be checked at a time, and an inner :class:`QHBoxLayout`
        keeps the group horizontally centred inside the toolbar row.
        A shared stylesheet makes the *checked* button visibly
        highlighted (theme accent fill, white text) so the user can
        see at a glance which mode is active.
        """
        self._changes_button = QPushButton("Changes only", self)
        self._changes_button.setCheckable(True)
        self._changes_button.setChecked(True)
        self._changes_button.setStyleSheet(self._BUTTON_STYLESHEET)
        self._changes_button.setCursor(Qt.CursorShape.PointingHandCursor)

        self._document_button = QPushButton("Full document", self)
        self._document_button.setCheckable(True)
        self._document_button.setStyleSheet(self._BUTTON_STYLESHEET)
        self._document_button.setCursor(Qt.CursorShape.PointingHandCursor)

        group_row = QHBoxLayout()
        group_row.setContentsMargins(0, 0, 0, 0)
        group_row.setSpacing(6)
        group_row.addStretch(1)
        group_row.addWidget(self._changes_button)
        group_row.addWidget(self._document_button)
        group_row.addStretch(1)

        self._mode_group = QButtonGroup(self)
        self._mode_group.setExclusive(True)
        self._mode_group.addButton(self._changes_button, int(DiffViewMode.CHANGES_ONLY))
        self._mode_group.addButton(self._document_button, int(DiffViewMode.FULL_DOCUMENT))
        self._mode_group.idClicked.connect(self._on_mode_button_clicked)

        self._toolbar = QWidget(self)
        toolbar_layout = QHBoxLayout(self._toolbar)
        # Equal top and bottom margin so the buttons sit visually
        # centred between the widget's top edge and the editor body
        # below — without the top margin the buttons hug the upper
        # edge while a chunk of empty space separates them from the
        # editor.
        toolbar_layout.setContentsMargins(0, _TOOLBAR_VERTICAL_MARGIN, 0, _TOOLBAR_VERTICAL_MARGIN)
        toolbar_layout.addLayout(group_row)

    def _layout_body(self) -> None:
        """Stack the toolbar on top of the editor and stretch the editor.

        The editor fills the rest of the widget, with the toolbar
        pinned at its preferred height (size policy: ``Maximum``).
        """
        root = QVBoxLayout(self)
        root.setContentsMargins(0, 0, 0, 0)
        root.setSpacing(0)
        root.addWidget(self._toolbar)
        root.addWidget(self._editor, 1)
        # The toolbar should not stretch — its preferred height is
        # the row's natural height — so the editor absorbs the rest.
        self._toolbar.setSizePolicy(
            self._toolbar.sizePolicy().horizontalPolicy(),
            self._toolbar.sizePolicy().verticalPolicy().Maximum,
        )

    # ── public API ────────────────────────────────────────────────

    def set_diff(self, text: str) -> None:
        """Set the *changes-only* diff content (legacy entry point).

        Equivalent to ``set_diff_pair(text, text)`` — i.e. the same
        text is also stored as the full-document variant. Existing
        callers from earlier stages pass only the changes-only text;
        passing the same string for both keeps the toolbar functional
        (toggling shows identical content) without forcing every
        caller to learn the new pair API.
        """
        self._changes_only_text = text
        # If no full-document variant was supplied yet, mirror the
        # changes-only text so the toolbar doesn't render an empty
        # editor when the user switches modes.
        if not self._full_document_text:
            self._full_document_text = text
        self._render()

    def set_full_document_diff(self, text: str) -> None:
        """Set the *full-document* variant of the diff.

        Use this in tandem with :meth:`set_diff` when the two variants
        are computed separately (the recommended path — recomputing the
        same diff twice is wasteful). If the changes-only text was set
        before, leave it alone; otherwise it stays empty and toggling
        to *Changes only* will clear the view.
        """
        self._full_document_text = text
        self._render()

    def set_diff_pair(self, changes_only_text: str, full_document_text: str) -> None:
        """Replace both variants of the diff at once and re-render.

        Passing both variants together is the preferred entry point
        for upstream code that pre-computes the two diffs (one with a
        small ``context_lines``, one with a very large one) — toggling
        modes then has no recompute cost.
        """
        self._changes_only_text = changes_only_text
        self._full_document_text = full_document_text
        self._render()

    def view_mode(self) -> DiffViewMode:
        """Return the currently active :class:`DiffViewMode`."""
        return self._view_mode

    def set_view_mode(self, mode: DiffViewMode) -> None:
        """Switch the active mode and re-render.

        Emits :attr:`view_mode_changed` when the mode actually changes.
        The toolbar's checked button is kept in sync so the UI stays
        consistent with programmatic switches (e.g. when the user
        closes and re-opens the same file).

        Both buttons' checked state is rewritten explicitly rather than
        relying on the ``QButtonGroup`` exclusivity dance — toggling
        ``setExclusive(False)`` mid-update leaves both buttons in the
        checked state when it is re-enabled, so the group would no
        longer reflect which mode is active.
        """
        if mode == self._view_mode:
            return
        self._view_mode = mode
        for candidate in DiffViewMode:
            btn = self._mode_group.button(int(candidate))
            if btn is not None:
                btn.setChecked(candidate == mode)
        self._render()
        self.view_mode_changed.emit(mode)

    def clear(self) -> None:
        """Remove all content, highlights, and cached diff text."""
        self._editor.clear()
        self._editor.set_line_info([])
        self._editor.setExtraSelections([])
        self._editor._diff_scrollbar.set_diff_blocks([], [])
        self._changes_only_text = ""
        self._full_document_text = ""

    def toPlainText(self) -> str:  # noqa: N802
        return self._editor.toPlainText()

    def isVisible(self) -> bool:  # noqa: N802
        return super().isVisible()

    def setVisible(self, visible: bool) -> None:  # noqa: N802
        super().setVisible(visible)

    # ── resize ────────────────────────────────────────────────────

    def resizeEvent(self, event) -> None:  # noqa: N802
        super().resizeEvent(event)
        # ``_layout_body`` already pinned the editor through the
        # vertical layout, so no manual geometry is required here —
        # the override exists only to keep the contract used by the
        # earlier stand-alone implementation.

    # ── internal: mode switching & rendering ──────────────────────

    def _on_mode_button_clicked(self, button_id: int) -> None:
        """Translate the toolbar click into a :meth:`set_view_mode` call."""
        try:
            mode = DiffViewMode(button_id)
        except ValueError:
            return
        self.set_view_mode(mode)

    def _render(self) -> None:
        """Paint the editor with whichever variant matches the active mode.

        Both variants are parsed (cheap — same string may be re-parsed
        on toggle) and the file-level headers are dropped before the
        document is rebuilt. Highlighting is applied last so the
        gutter widths line up with the line-info array.

        After painting the editor pushes the deletion/addition
        positions to the custom scrollbar's minimap. In *Full
        document* mode the view also scrolls to the first diff line
        so the user immediately sees the change when they switch
        modes on a long file.
        """
        if self._view_mode == DiffViewMode.CHANGES_ONLY:
            text = self._changes_only_text
        else:
            text = self._full_document_text
        parsed = parse_diff_lines(text)
        # Drop file-level headers — they're noise in a per-file view.
        # Hunk markers, additions, deletions, context, and the
        # ``\\ No newline at end of file`` marker all stay.
        kept = [p for p in parsed if p.line_type != DiffLineType.HEADER]
        self._editor.set_line_info(kept)
        self._editor.setPlainText("\n".join(p.text for p in kept))
        self._apply_highlighting(kept)
        self._editor.update_diff_markers(kept)
        if self._view_mode == DiffViewMode.FULL_DOCUMENT:
            self._scroll_to_first_diff()

    def _scroll_to_first_diff(self) -> None:
        """Place the first deletion or addition at the top of the view.

        Only invoked in :attr:`DiffViewMode.FULL_DOCUMENT` mode where
        the whole file is rendered and the first change may be far
        down the document; without this the user sees the file head
        and has to scroll past hundreds of unchanged lines to find
        the diff.

        The cursor is reset (not extended) so any previous selection
        is collapsed cleanly. We schedule the actual ``scrollContentsBy``
        via a zero-delay :class:`QTimer` so the layout engine has a
        chance to compute the new ``maximum()`` and block heights
        before we ask the editor to scroll.
        """
        line_info = self._editor._line_info
        target_idx: int | None = None
        for idx, info in enumerate(line_info):
            if info.line_type in (DiffLineType.ADDITION, DiffLineType.DELETION):
                target_idx = idx
                break
        if target_idx is None:
            return
        block = self._editor.document().findBlockByLineNumber(target_idx)
        if not block.isValid():
            return
        cursor = QTextCursor(block)

        def _do_scroll() -> None:
            self._editor.setTextCursor(cursor)
            self._editor.ensureCursorVisible()

        QTimer.singleShot(0, _do_scroll)

    # ── highlighting ──────────────────────────────────────────────

    def _apply_highlighting(self, line_info: list[ParsedDiffLine]) -> None:
        """Paint backgrounds for each visible block based on *line_info*."""
        doc: QTextDocument = self._editor.document()
        selections: list[ExtraSelection] = []
        for idx, info in enumerate(line_info):
            bg, fg = _colours_for(info.line_type)
            if bg is None and fg is None:
                continue
            block = doc.findBlockByLineNumber(idx)
            if not block.isValid():
                continue
            cursor = QTextCursor(block)
            cursor.movePosition(QTextCursor.MoveOperation.StartOfBlock)
            cursor.movePosition(
                QTextCursor.MoveOperation.EndOfBlock, QTextCursor.MoveMode.KeepAnchor,
            )
            fmt = QTextCharFormat()
            if bg is not None:
                fmt.setBackground(bg)
            if fg is not None:
                fmt.setForeground(fg)
            es = ExtraSelection()
            es.cursor = cursor
            es.format = fmt
            selections.append(es)
        self._editor.setExtraSelections(selections)


# ── helpers ───────────────────────────────────────────────────────────


def _colours_for(line_type: DiffLineType) -> tuple[QColor | None, QColor | None]:
    return _TYPE_COLOURS.get(line_type, (None, None))


_TYPE_COLOURS: dict[DiffLineType, tuple[QColor | None, QColor | None]] = {
    DiffLineType.ADDITION: (ADDITION_BG, ADDITION_FG),
    DiffLineType.DELETION: (DELETION_BG, DELETION_FG),
    DiffLineType.HUNK: (HUNK_BG, HUNK_FG),
    DiffLineType.CONTEXT: (None, None),
    DiffLineType.EMPTY: (None, None),
    # HEADER colour slots are intentionally absent — the widget
    # filters these lines out before they reach the document.
}


__all__ = ["DiffViewMode", "DiffViewWidget"]
