"""Colour-coded diff view with line-number gutter.

Replaces the plain ``QPlainTextEdit`` that was used through Stage 3-8 as
a temporary diff viewer. Uses :func:`src.core.diff_parser.parse_diff_lines`
to classify each line and paints backgrounds accordingly:

* Additions  — green-tinted background
* Deletions  — red-tinted background
* Hunk headers (``@@ … @@``) — cyan-tinted background
* Context / empty lines — transparent (the editor background shows through)

A gutter on the left draws the **file** line number for each change —
additions and context use the new-file line, deletions use the
old-file line, both derived from the parsed hunk header. The user
sees "this addition lives on line 42 of the file" rather than a
sequential 1, 2, 3 … diff index.

File-level header lines (``diff --git``, ``index``, ``--- a/…``,
``+++ b/…``, ``old mode``, etc.) are not displayed: the viewer is
opened from a specific file, so the file header is redundant noise.

The widget is read-only and has no file-io or Git logic — it only
receives a diff string via :meth:`set_diff`.

View modes
----------
The top of the widget carries a small centred toolbar with two checkable
buttons that toggle between **Changes only** and **Full document**:

* **Changes only** (default) — the diff as generated by ``git diff`` with
  ``context_lines=3``, just like every prior version. Best when the user
  only wants to see what changed.
* **Full document** — the same file rendered with effectively unlimited
  context so every line of both versions is present. The additions,
  deletions and hunks appear in the same colour-coded form as in the
  changes-only view; only the unchanged context expands to cover the
  whole file.

The widget stores both variants of the diff text and renders whichever
matches the active mode, so toggling is instant (no re-diff needed).
Upstream code is expected to call :meth:`set_diff_pair` (or the legacy
:meth:`set_diff` + :meth:`set_full_document_diff`) when a new file is
selected; the toolbar then decides which variant to show.
"""
from __future__ import annotations

from enum import IntEnum

from PySide6.QtCore import QRect, QSize, Qt, Signal
from PySide6.QtGui import (
    QColor,
    QFont,
    QPainter,
    QTextCharFormat,
    QTextCursor,
    QTextDocument,
)
from PySide6.QtWidgets import (
    QButtonGroup,
    QHBoxLayout,
    QPlainTextEdit,
    QPushButton,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from src.core.diff_parser import DiffLineType, ParsedDiffLine, parse_diff_lines

# ── diff colour palette ───────────────────────────────────────────────
ADDITION_BG = QColor(26, 64, 32)
DELETION_BG = QColor(64, 32, 32)
HUNK_BG = QColor(26, 48, 64)
GUTTER_BG = QColor(21, 21, 21)
GUTTER_FG = QColor(90, 90, 90)
ADDITION_FG = QColor(172, 229, 172)
DELETION_FG = QColor(229, 172, 172)
HUNK_FG = QColor(140, 190, 210)
# ──────────────────────────────────────────────────────────────────────

ExtraSelection = QTextEdit.ExtraSelection

# How many characters of padding to leave on the right edge of the
# gutter before the diff text starts. Mirrors the value the old
# implementation used (digits + 3).
_GUTTER_RIGHT_PADDING_CHARS = 3

# Border between the toolbar and the editor. Mirrors a QFrame default
# so the toolbar reads as "attached" to the editor without borrowing
# focus colours from the rest of the app.
_TOOLBAR_BOTTOM_MARGIN = 4


class DiffViewMode(IntEnum):
    """What the diff pane should display."""

    CHANGES_ONLY = 0
    FULL_DOCUMENT = 1


class _LineNumberArea(QWidget):
    """Left gutter that paints the file line number for each block."""

    def __init__(self, editor: _DiffEditor) -> None:
        super().__init__(editor)
        self._editor = editor

    def sizeHint(self) -> QSize:  # noqa: N802
        return QSize(self._editor.gutter_width(), 0)

    def paintEvent(self, event) -> None:  # noqa: N802
        painter = QPainter(self)
        painter.fillRect(event.rect(), GUTTER_BG)
        block = self._editor.firstVisibleBlock()
        top = round(
            self._editor.blockBoundingGeometry(block)
            .translated(self._editor.contentOffset())
            .top()
        )
        bottom = top + round(self._editor.blockBoundingRect(block).height())
        fm = self._editor.fontMetrics()
        w = self.width() - fm.horizontalAdvance("9")
        line_info = self._editor._line_info
        while block.isValid() and top <= event.rect().bottom():
            if block.isVisible() and bottom >= event.rect().top():
                block_num = block.blockNumber()
                line_number = (
                    line_info[block_num].line_number
                    if block_num < len(line_info)
                    else None
                )
                if line_number is not None:
                    painter.setPen(GUTTER_FG)
                    painter.drawText(
                        0,
                        top,
                        w,
                        fm.height(),
                        Qt.AlignmentFlag.AlignRight,
                        str(line_number),
                    )
            block = block.next()
            top = bottom
            bottom = top + round(self._editor.blockBoundingRect(block).height())
        painter.end()


class _DiffEditor(QPlainTextEdit):
    """Internal plain-text editor that collaborates with the gutter."""

    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self.setReadOnly(True)
        self.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.setFont(QFont("Consolas", 10))
        self.setTabStopDistance(40)
        # Parallel to the editor's blocks: for each visible block we
        # remember its semantic type and (when applicable) the real
        # file line number, so the gutter can paint the file row
        # instead of a sequential index.
        self._line_info: list[ParsedDiffLine] = []
        self._line_number_area = _LineNumberArea(self)
        self.blockCountChanged.connect(self._update_gutter_width)
        self.updateRequest.connect(self._update_line_number_area)

    def gutter_width(self) -> int:
        """Width required to fit the longest line number we display.

        Sized off the maximum file line number (not the visible block
        count) so a single-line change in a 1000-line file still gets
        a 4-digit gutter.
        """
        max_block = max(self.blockCount(), 1)
        max_line = max(
            (info.line_number for info in self._line_info if info.line_number),
            default=0,
        )
        digits = len(str(max(max_block, max_line)))
        digits = max(1, digits)
        fm = self.fontMetrics()
        return fm.horizontalAdvance("9") * (digits + _GUTTER_RIGHT_PADDING_CHARS)

    def line_number_area_width(self) -> int:
        return self.gutter_width()

    def set_line_info(self, line_info: list[ParsedDiffLine]) -> None:
        """Replace the parallel block-to-line mapping.

        Must be called whenever the editor's text changes so block N
        in the document still corresponds to the right
        :class:`ParsedDiffLine`.
        """
        self._line_info = list(line_info)
        # Recompute gutter width now that the max line number may
        # have changed; ``blockCountChanged`` only fires when the
        # number of blocks changes, not when their metadata does.
        self._update_gutter_width()

    # ── internal slots connected to signals ───────────────────────

    def _update_gutter_width(self, _new_block_count: int = 0) -> None:
        self.setViewportMargins(self.gutter_width(), 0, 0, 0)

    def _update_line_number_area(self, rect: QRect, dy: int) -> None:
        if dy:
            self._line_number_area.scroll(0, dy)
        else:
            self._line_number_area.update(
                0, rect.y(), self._line_number_area.width(), rect.height(),
            )
        if rect.contains(self.viewport().rect()):
            self._update_gutter_width()

    def resizeEvent(self, event) -> None:  # noqa: N802
        super().resizeEvent(event)
        cr = self.contentsRect()
        self._line_number_area.setGeometry(
            cr.left(), cr.top(), self.gutter_width(), cr.height(),
        )


class DiffViewWidget(QWidget):
    """Colour-coded, read-only diff viewer with a line-number gutter.

    Usage
    -----
    >>> view = DiffViewWidget(parent)
    >>> view.set_diff(diff_text)                     # changes-only text
    >>> view.set_full_document_diff(full_diff_text)  # full-document text
    >>> view.set_view_mode(DiffViewMode.FULL_DOCUMENT)
    >>> view.clear()

    A two-button toolbar at the top lets the user flip between
    *Changes only* and *Full document*; the rest of the widget is the
    colour-coded diff pane described in the module docstring. Callers
    that pre-compute both variants should hand them to
    :meth:`set_diff_pair` to keep toggling instantaneous.

    File-level header lines (``diff --git`` / ``---`` / ``+++`` /
    ``index`` / mode lines) are not shown — the user picked this
    view from a specific file, so the header is redundant. The
    gutter paints the actual file line number for every change so
    the reader can see "this addition is on line 42 of the file"
    instead of a sequential diff index.
    """

    view_mode_changed = Signal(object)
    """Emitted with the new :class:`DiffViewMode` when the user toggles
    the toolbar buttons (also fires when the mode is set programmatically
    via :meth:`set_view_mode`, but only when the value actually changes)."""

    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self._editor = _DiffEditor(self)
        self._changes_only_text: str = ""
        self._full_document_text: str = ""
        self._view_mode: DiffViewMode = DiffViewMode.CHANGES_ONLY
        self._build_toolbar()
        self._layout_body()

    # ── layout ────────────────────────────────────────────────────

    def _build_toolbar(self) -> None:
        """Create the two-mode toggle buttons that sit above the editor.

        The buttons are wrapped in a :class:`QButtonGroup` so only one
        can be checked at a time, and an inner :class:`QHBoxLayout`
        keeps the group horizontally centred inside the toolbar row.
        """
        self._changes_button = QPushButton("Changes only", self)
        self._changes_button.setCheckable(True)
        self._changes_button.setChecked(True)
        self._document_button = QPushButton("Full document", self)
        self._document_button.setCheckable(True)

        group_row = QHBoxLayout()
        group_row.setContentsMargins(0, 0, 0, 0)
        group_row.setSpacing(6)
        group_row.addStretch(1)
        group_row.addWidget(self._changes_button)
        group_row.addWidget(self._document_button)
        group_row.addStretch(1)

        self._mode_group = QButtonGroup(self)
        self._mode_group.setExclusive(True)
        self._mode_group.addButton(self._changes_button, int(DiffViewMode.CHANGES_ONLY))
        self._mode_group.addButton(self._document_button, int(DiffViewMode.FULL_DOCUMENT))
        self._mode_group.idClicked.connect(self._on_mode_button_clicked)

        self._toolbar = QWidget(self)
        toolbar_layout = QHBoxLayout(self._toolbar)
        toolbar_layout.setContentsMargins(0, 0, 0, _TOOLBAR_BOTTOM_MARGIN)
        toolbar_layout.addLayout(group_row)

    def _layout_body(self) -> None:
        """Stack the toolbar on top of the editor and stretch the editor.

        The editor fills the rest of the widget, with the toolbar
        pinned at its preferred height (size policy: ``Maximum``).
        """
        root = QVBoxLayout(self)
        root.setContentsMargins(0, 0, 0, 0)
        root.setSpacing(0)
        root.addWidget(self._toolbar)
        root.addWidget(self._editor, 1)
        # The toolbar should not stretch — its preferred height is
        # the row's natural height — so the editor absorbs the rest.
        self._toolbar.setSizePolicy(
            self._toolbar.sizePolicy().horizontalPolicy(),
            self._toolbar.sizePolicy().verticalPolicy().Maximum,
        )

    # ── public API ────────────────────────────────────────────────

    def set_diff(self, text: str) -> None:
        """Set the *changes-only* diff content (legacy entry point).

        Equivalent to ``set_diff_pair(text, text)`` — i.e. the same
        text is also stored as the full-document variant. Existing
        callers from earlier stages pass only the changes-only text;
        passing the same string for both keeps the toolbar functional
        (toggling shows identical content) without forcing every
        caller to learn the new pair API.
        """
        self._changes_only_text = text
        # If no full-document variant was supplied yet, mirror the
        # changes-only text so the toolbar doesn't render an empty
        # editor when the user switches modes.
        if not self._full_document_text:
            self._full_document_text = text
        self._render()

    def set_full_document_diff(self, text: str) -> None:
        """Set the *full-document* variant of the diff.

        Use this in tandem with :meth:`set_diff` when the two variants
        are computed separately (the recommended path — recomputing the
        same diff twice is wasteful). If the changes-only text was set
        before, leave it alone; otherwise it stays empty and toggling
        to *Changes only* will clear the view.
        """
        self._full_document_text = text
        self._render()

    def set_diff_pair(self, changes_only_text: str, full_document_text: str) -> None:
        """Replace both variants of the diff at once and re-render.

        Passing both variants together is the preferred entry point
        for upstream code that pre-computes the two diffs (one with a
        small ``context_lines``, one with a very large one) — toggling
        modes then has no recompute cost.
        """
        self._changes_only_text = changes_only_text
        self._full_document_text = full_document_text
        self._render()

    def view_mode(self) -> DiffViewMode:
        """Return the currently active :class:`DiffViewMode`."""
        return self._view_mode

    def set_view_mode(self, mode: DiffViewMode) -> None:
        """Switch the active mode and re-render.

        Emits :attr:`view_mode_changed` when the mode actually changes.
        The toolbar's checked button is kept in sync so the UI stays
        consistent with programmatic switches (e.g. when the user
        closes and re-opens the same file).
        """
        if mode == self._view_mode:
            return
        self._view_mode = mode
        # Update the button group without re-triggering the click
        # handler that drives :meth:`_on_mode_button_clicked`.
        sender = self._mode_group.button(int(mode))
        if sender is not None:
            self._mode_group.setExclusive(False)
            sender.setChecked(True)
            self._mode_group.setExclusive(True)
        self._render()
        self.view_mode_changed.emit(mode)

    def clear(self) -> None:
        """Remove all content, highlights, and cached diff text."""
        self._editor.clear()
        self._editor.set_line_info([])
        self._editor.setExtraSelections([])
        self._changes_only_text = ""
        self._full_document_text = ""

    def toPlainText(self) -> str:  # noqa: N802
        return self._editor.toPlainText()

    def isVisible(self) -> bool:  # noqa: N802
        return super().isVisible()

    def setVisible(self, visible: bool) -> None:  # noqa: N802
        super().setVisible(visible)

    # ── resize ────────────────────────────────────────────────────

    def resizeEvent(self, event) -> None:  # noqa: N802
        super().resizeEvent(event)
        # ``_layout_body`` already pinned the editor through the
        # vertical layout, so no manual geometry is required here —
        # the override exists only to keep the contract used by the
        # earlier stand-alone implementation.

    # ── internal: mode switching & rendering ──────────────────────

    def _on_mode_button_clicked(self, button_id: int) -> None:
        """Translate the toolbar click into a :meth:`set_view_mode` call."""
        try:
            mode = DiffViewMode(button_id)
        except ValueError:
            return
        self.set_view_mode(mode)

    def _render(self) -> None:
        """Paint the editor with whichever variant matches the active mode.

        Both variants are parsed (cheap — same string may be re-parsed
        on toggle) and the file-level headers are dropped before the
        document is rebuilt. Highlighting is applied last so the
        gutter widths line up with the line-info array.
        """
        if self._view_mode == DiffViewMode.CHANGES_ONLY:
            text = self._changes_only_text
        else:
            text = self._full_document_text
        parsed = parse_diff_lines(text)
        # Drop file-level headers — they're noise in a per-file view.
        # Hunk markers, additions, deletions, context, and the
        # ``\\ No newline at end of file`` marker all stay.
        kept = [p for p in parsed if p.line_type != DiffLineType.HEADER]
        self._editor.set_line_info(kept)
        self._editor.setPlainText("\n".join(p.text for p in kept))
        self._apply_highlighting(kept)

    # ── highlighting ──────────────────────────────────────────────

    def _apply_highlighting(self, line_info: list[ParsedDiffLine]) -> None:
        """Paint backgrounds for each visible block based on *line_info*."""
        doc: QTextDocument = self._editor.document()
        selections: list[ExtraSelection] = []
        for idx, info in enumerate(line_info):
            bg, fg = _colours_for(info.line_type)
            if bg is None and fg is None:
                continue
            block = doc.findBlockByLineNumber(idx)
            if not block.isValid():
                continue
            cursor = QTextCursor(block)
            cursor.movePosition(QTextCursor.MoveOperation.StartOfBlock)
            cursor.movePosition(
                QTextCursor.MoveOperation.EndOfBlock, QTextCursor.MoveMode.KeepAnchor,
            )
            fmt = QTextCharFormat()
            if bg is not None:
                fmt.setBackground(bg)
            if fg is not None:
                fmt.setForeground(fg)
            es = ExtraSelection()
            es.cursor = cursor
            es.format = fmt
            selections.append(es)
        self._editor.setExtraSelections(selections)


# ── helpers ───────────────────────────────────────────────────────────


def _colours_for(line_type: DiffLineType) -> tuple[QColor | None, QColor | None]:
    return _TYPE_COLOURS.get(line_type, (None, None))


_TYPE_COLOURS: dict[DiffLineType, tuple[QColor | None, QColor | None]] = {
    DiffLineType.ADDITION: (ADDITION_BG, ADDITION_FG),
    DiffLineType.DELETION: (DELETION_BG, DELETION_FG),
    DiffLineType.HUNK: (HUNK_BG, HUNK_FG),
    DiffLineType.CONTEXT: (None, None),
    DiffLineType.EMPTY: (None, None),
    # HEADER colour slots are intentionally absent — the widget
    # filters these lines out before they reach the document.
}


__all__ = ["DiffViewMode", "DiffViewWidget"]
